# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoseo', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mymetadatamodel',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='mymetadatamodel',
            name='_content_type',
        ),
        migrations.DeleteModel(
            name='MyMetadataView',
        ),
        migrations.AlterModelOptions(
            name='mymetadatamodelinstance',
            options={'verbose_name': 'SEO (Model Instance)', 'verbose_name_plural': 'SEO (Model Instance)'},
        ),
        migrations.AlterModelOptions(
            name='mymetadatapath',
            options={'verbose_name': 'SEO (Path)', 'verbose_name_plural': 'SEO (Path)'},
        ),
        migrations.AlterField(
            model_name='mymetadatamodelinstance',
            name='description',
            field=models.CharField(blank=True, default='', help_text='Краткое описание содержимого страницы. Это будет отображаться в результатах поиска.', max_length=155),
        ),
        migrations.AlterField(
            model_name='mymetadatamodelinstance',
            name='heading',
            field=models.CharField(blank=True, default='', help_text='Это будет отображаться в элементе h1.', max_length=511),
        ),
        migrations.AlterField(
            model_name='mymetadatamodelinstance',
            name='keywords',
            field=models.CharField(blank=True, default='', help_text='Список слов или фраз, разделенных запятыми, которые описывают контент.', max_length=511),
        ),
        migrations.AlterField(
            model_name='mymetadatamodelinstance',
            name='title',
            field=models.CharField(blank=True, default='', help_text='Это будет отображаться в названии окна / вкладки, а также в результатах поиска.', max_length=68),
        ),
        migrations.AlterField(
            model_name='mymetadatapath',
            name='description',
            field=models.CharField(blank=True, default='', help_text='Краткое описание содержимого страницы. Это будет отображаться в результатах поиска.', max_length=155),
        ),
        migrations.AlterField(
            model_name='mymetadatapath',
            name='heading',
            field=models.CharField(blank=True, default='', help_text='Это будет отображаться в элементе h1.', max_length=511),
        ),
        migrations.AlterField(
            model_name='mymetadatapath',
            name='keywords',
            field=models.CharField(blank=True, default='', help_text='Список слов или фраз, разделенных запятыми, которые описывают контент.', max_length=511),
        ),
        migrations.AlterField(
            model_name='mymetadatapath',
            name='title',
            field=models.CharField(blank=True, default='', help_text='Это будет отображаться в названии окна / вкладки, а также в результатах поиска.', max_length=68),
        ),
        migrations.DeleteModel(
            name='MyMetadataModel',
        ),
    ]
