# Generated by Django 2.2.17 on 2021-01-06 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20180107_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='weight',
            field=models.PositiveSmallIntegerField(default=1000, help_text='Чем больше значение, тем выше страница в списке.', verbose_name='Вес'),
        ),
    ]
