# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 09:05
from __future__ import unicode_literals

import apps.people.models
import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('theater', '0019_auto_20171123_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentPlay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст')),
            ],
        ),
        migrations.CreateModel(
            name='LastPlay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(default='', max_length=255, unique=True, verbose_name='Slug (для url)')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Включено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('slug', models.SlugField(default='', max_length=255, unique=True, verbose_name='Slug (для url)')),
                ('image', models.ImageField(blank=True, help_text='Оптимальный размер: 400px*550px.', null=True, upload_to='people/', verbose_name='Фото')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('education', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО')),
                ('prizes', models.TextField(blank=True, null=True, verbose_name='Награды')),
                ('ranks', models.TextField(blank=True, null=True, verbose_name='Звания')),
                ('biography', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Биография')),
                ('has_page', models.BooleanField(default=True, verbose_name='Есть собственная страница?')),
                ('current_plays', models.ManyToManyField(related_name='current_plays', through='people.CurrentPlay', to='theater.Play')),
                ('last_plays', models.ManyToManyField(related_name='last_plays', through='people.LastPlay', to='theater.Play')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='PersonPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Оптимальный размер: 800px*500px.', upload_to=apps.people.models.PersonPhoto.upload_to, verbose_name='Изображение')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Включено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Person', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('weight', models.PositiveIntegerField(default=10000, help_text='Чем выше вес, тем "выше" сотрудник с этой должностью на странице.', verbose_name='Вес')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.AddField(
            model_name='person',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Position', verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='page',
            name='persons',
            field=models.ManyToManyField(to='people.Person', verbose_name='Сотрудники'),
        ),
        migrations.AddField(
            model_name='lastplay',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Person'),
        ),
        migrations.AddField(
            model_name='lastplay',
            name='play',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theater.Play'),
        ),
        migrations.AddField(
            model_name='currentplay',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Person'),
        ),
        migrations.AddField(
            model_name='currentplay',
            name='play',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theater.Play'),
        ),
    ]
