# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-05 10:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_vacations_vacationspage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vacations',
            new_name='Vacation',
        ),
    ]
