# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 10:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20171127_1120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currentplay',
            options={'verbose_name': 'Спектакль', 'verbose_name_plural': 'Текущие спектакли'},
        ),
        migrations.AlterModelOptions(
            name='lastplay',
            options={'verbose_name': 'Спектакль', 'verbose_name_plural': 'Спектакли прошлых лет'},
        ),
        migrations.AlterModelOptions(
            name='personphoto',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Галерея'},
        ),
        migrations.AlterField(
            model_name='currentplay',
            name='play',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theater.Play', verbose_name='Спектакль'),
        ),
        migrations.AlterField(
            model_name='lastplay',
            name='play',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theater.Play', verbose_name='Спектакль'),
        ),
        migrations.AlterField(
            model_name='page',
            name='persons',
            field=models.ManyToManyField(blank=True, null=True, to='people.Person', verbose_name='Сотрудники'),
        ),
        migrations.AlterField(
            model_name='person',
            name='current_plays',
            field=models.ManyToManyField(blank=True, null=True, related_name='current_plays', through='people.CurrentPlay', to='theater.Play'),
        ),
        migrations.AlterField(
            model_name='person',
            name='education',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Образование'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_plays',
            field=models.ManyToManyField(blank=True, null=True, related_name='last_plays', through='people.LastPlay', to='theater.Play'),
        ),
    ]
