# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-05 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20180105_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation',
            name='count',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Количество необходимых кадров'),
        ),
    ]
