# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20171127_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='persons',
            field=models.ManyToManyField(blank=True, to='theater.Person', verbose_name='Сотрудники'),
        ),
        migrations.AlterField(
            model_name='person',
            name='current_plays',
            field=models.ManyToManyField(blank=True, related_name='current_plays', through='theater.CurrentPlay', to='theater.Play'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_plays',
            field=models.ManyToManyField(blank=True, related_name='last_plays', through='theater.LastPlay', to='theater.Play'),
        ),
    ]
