# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_auto_20171127_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentplay',
            name='person',
        ),
        migrations.RemoveField(
            model_name='currentplay',
            name='play',
        ),
        migrations.RemoveField(
            model_name='lastplay',
            name='person',
        ),
        migrations.RemoveField(
            model_name='lastplay',
            name='play',
        ),
        migrations.RemoveField(
            model_name='person',
            name='current_plays',
        ),
        migrations.RemoveField(
            model_name='person',
            name='last_plays',
        ),
        migrations.RemoveField(
            model_name='person',
            name='position',
        ),
        migrations.RemoveField(
            model_name='personphoto',
            name='person',
        ),
        migrations.DeleteModel(
            name='CurrentPlay',
        ),
        migrations.DeleteModel(
            name='LastPlay',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='PersonPhoto',
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
