# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-05 11:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_auto_20180105_1253'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VacationsPage',
            new_name='VacanciesPage',
        ),
        migrations.RenameModel(
            old_name='Vacation',
            new_name='Vacancy',
        ),
    ]
