version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && gunicorn sevtuz.wsgi -b 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8001:8000"
    depends_on:
      - db