# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playbill', '0004_auto_20171120_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='external',
            field=models.BooleanField(default=False, verbose_name='Выездной спектакль'),
        ),
    ]
