# Generated by Django 2.0.7 on 2018-09-09 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playbill', '0004_event_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='show_for_all',
            field=models.BooleanField(default=False, verbose_name='Показывать всем в служебном кабинете?'),
        ),
    ]
