# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 12:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('theater', '0029_auto_20171228_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='Дата и время начала')),
                ('free_enter', models.BooleanField(default=False, verbose_name='Свободный вход')),
                ('is_premiere', models.BooleanField(default=False, verbose_name='Премьера')),
                ('gts', models.BooleanField(default=False, verbose_name='ГТС')),
                ('external', models.BooleanField(default=False, verbose_name='Выездной спектакль')),
                ('tour', models.BooleanField(default=False, verbose_name='Гастроли')),
                ('guests', models.BooleanField(default=False, verbose_name='Наши гости / к нам едут')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Включено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('play', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theater.Play', verbose_name='Спектакль')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
            },
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('show_in_filter', models.BooleanField(default=False, help_text='Показывать в фильтре на странице "Репертуар"', verbose_name='Показывать в фильтре')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Сцена',
                'verbose_name_plural': 'Сцены',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='scene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playbill.Scene', verbose_name='Сцена'),
        ),
    ]
