# Generated by Django 2.0.7 on 2018-07-13 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playbill', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='radario_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID события в системе Radario'),
        ),
    ]
