# Generated by Django 2.0.7 on 2018-08-21 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0037_auto_20180821_0931'),
        ('playbill', '0003_auto_20180819_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(blank=True, to='theater.Person', verbose_name='Участники'),
        ),
    ]
