# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 12:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'Данные страницы', 'verbose_name_plural': 'Данные страницы'},
        ),
    ]
