# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 13:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0006_auto_20171117_1523'),
        ('repertoire', '0002_auto_20171117_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='play',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='theater.Play', verbose_name='Спектакль'),
            preserve_default=False,
        ),
    ]
