# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 11:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repertoire', '0003_event_play'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Событие', 'verbose_name_plural': 'События'},
        ),
        migrations.AlterModelOptions(
            name='scene',
            options={'verbose_name': 'Сцена', 'verbose_name_plural': 'Сцены'},
        ),
    ]
