# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repertoire', '0006_event_guests'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='show_in_filter',
            field=models.BooleanField(default=False, help_text='Показывать в фильтре на странице "Репертуар"', verbose_name='Показывать в фильтре'),
        ),
    ]
