# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 19:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repertoire', '0006_event_guests'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(help_text='Оптимальный размер: 1140px*590px.', upload_to='home', verbose_name='Изображение')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repertoire.Event', verbose_name='Событие')),
            ],
            options={
                'verbose_name': 'Главное событие',
                'verbose_name_plural': 'Главное событие',
            },
        ),
    ]
