# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-09 20:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0034_auto_20180109_2238'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playbill',
            options={'verbose_name': 'Афиша главной страницы', 'verbose_name_plural': 'Афиша главной страницы'},
        ),
        migrations.RemoveField(
            model_name='playbill',
            name='event',
        ),
        migrations.AddField(
            model_name='playbill',
            name='play',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='theater.Play', verbose_name='Спектакль'),
            preserve_default=False,
        ),
    ]
