# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 11:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainevent',
            name='event',
            field=models.ForeignKey(help_text='Здесь показаны только будущие события', on_delete=django.db.models.deletion.CASCADE, to='repertoire.Event', verbose_name='Событие'),
        ),
    ]
