# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 13:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20171123_1340'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MainEvent',
            new_name='Playbill',
        ),
    ]
