# Generated by Django 2.0.7 on 2018-09-09 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff_office', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='office',
            options={'verbose_name': 'Страница "Контора"', 'verbose_name_plural': 'Страница "Контора"'},
        ),
    ]
