# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-25 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'Страница', 'verbose_name_plural': 'Страницы'},
        ),
        migrations.AddField(
            model_name='page',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Включено'),
        ),
        migrations.AddField(
            model_name='page',
            name='slug',
            field=models.SlugField(default='', max_length=255, unique=True, verbose_name='Slug (для url)'),
        ),
        migrations.AddField(
            model_name='page',
            name='title',
            field=models.CharField(default='', max_length=255, verbose_name='Заголовок'),
            preserve_default=False,
        ),
    ]
