# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information_block_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок текстового блока')),
                ('information_block_text', models.TextField(blank=True, null=True, verbose_name='Текст блока (html)')),
                ('contacts_block_html', models.TextField(blank=True, null=True, verbose_name='Текст блока "Контакты" (html)')),
            ],
            options={
                'verbose_name': 'Footer',
                'verbose_name_plural': 'Footer',
            },
        ),
    ]
