# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_auto_20171217_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footersettings',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефон'),
        ),
    ]
