# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 12:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('playbill', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playbill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(help_text='Оптимальный размер: 1140px*590px.', upload_to='home', verbose_name='Изображение')),
                ('event', models.ForeignKey(help_text='Здесь показаны только будущие события', on_delete=django.db.models.deletion.CASCADE, to='playbill.Event', verbose_name='Событие')),
            ],
            options={
                'verbose_name': 'Афиша главного события',
                'verbose_name_plural': 'Афиша главного события',
            },
        ),
    ]
