# Generated by Django 2.2.17 on 2021-09-29 09:02

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180109_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playbill',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(help_text='Оптимальный размер: 1920px по ширине.', upload_to='home', verbose_name='Изображение'),
        ),
    ]
