# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='month_from',
            field=models.PositiveIntegerField(choices=[(0, 'Январь'), (1, 'Февраль'), (2, 'Март'), (3, 'Апрель'), (4, 'Май'), (5, 'Июнь'), (6, 'Июль'), (7, 'Август'), (8, 'Сентябрь'), (9, 'Октябрь'), (10, 'Ноябрь'), (11, 'Декабрь')], default=None, verbose_name='Месяц с'),
        ),
        migrations.AddField(
            model_name='season',
            name='month_to',
            field=models.PositiveIntegerField(choices=[(0, 'Январь'), (1, 'Февраль'), (2, 'Март'), (3, 'Апрель'), (4, 'Май'), (5, 'Июнь'), (6, 'Июль'), (7, 'Август'), (8, 'Сентябрь'), (9, 'Октябрь'), (10, 'Ноябрь'), (11, 'Декабрь')], default=None, verbose_name='Месяц по'),
        ),
        migrations.AddField(
            model_name='season',
            name='year_from',
            field=models.PositiveIntegerField(default=None, verbose_name='Год с'),
        ),
        migrations.AddField(
            model_name='season',
            name='year_to',
            field=models.PositiveIntegerField(default=None, verbose_name='Год по'),
        ),
    ]
