# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0006_auto_20171117_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='play',
            name='duration',
        ),
        migrations.AddField(
            model_name='play',
            name='duration',
            field=models.DurationField(blank=True, null=True, verbose_name='Продолжительность, минут'),
        ),
    ]
