# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0010_play_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play',
            name='slug',
            field=models.SlugField(default='', max_length=255, unique=True, verbose_name='Slug (для url)'),
        ),
    ]
