# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 12:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0012_auto_20171122_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_id', models.CharField(help_text='Например, для видео https://www.youtube.com/watch?v=ZyMByVSIEKE, его идентификатором будет ZyMByVSIEKE.', max_length=10, verbose_name='Идентификатор на Youtube')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Включено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('play', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theater.Play', verbose_name='Спектакль')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
            },
        ),
    ]
