# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0016_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='slug',
            field=models.SlugField(default='', max_length=255, verbose_name='Slug (для url)'),
        ),
    ]
