# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0017_page_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(default='', max_length=255, unique=True, verbose_name='Slug (для url)'),
        ),
    ]
