# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0018_auto_20171123_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='is_our_play',
            field=models.BooleanField(default=True, verbose_name='Спектакль нашего театра (отображать на странице "Спектакли")?'),
        ),
        migrations.AddField(
            model_name='play',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Текущий'), (2, 'Архивный'), (3, 'Планируемый')], default=1, verbose_name='Статус спектакля'),
        ),
    ]
