# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 09:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0020_auto_20171128_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonPlayRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=255, null=True, verbose_name='Роль')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theater.Person')),
                ('play', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theater.Play', verbose_name='Спектакль')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
            },
        ),
        migrations.AddField(
            model_name='play',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='roles', through='theater.PersonPlayRole', to='theater.Person'),
        ),
    ]
