# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-25 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0023_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, help_text='Оптимальный размер: 800px*500px.', null=True, upload_to='news', verbose_name='Изображение'),
        ),
    ]
