# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-26 08:31
from __future__ import unicode_literals

import apps.theater.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0025_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Оптимальный размер: 800px*500px.', upload_to=apps.theater.models.HistoryPhoto.upload_to, verbose_name='Изображение')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Включено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.CreateModel(
            name='HistoryVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_id', models.CharField(help_text='Например, для видео https://www.youtube.com/watch?v=JMJXvsCLu6, его идентификатором будет JMJXvsCLu6.', max_length=32, verbose_name='Идентификатор на Youtube')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Включено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
            },
        ),
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name': 'История сезона', 'verbose_name_plural': 'История'},
        ),
        migrations.AddField(
            model_name='historyvideo',
            name='history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theater.History', verbose_name='Сезон'),
        ),
        migrations.AddField(
            model_name='historyphoto',
            name='history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theater.History', verbose_name='Сезон'),
        ),
    ]
