# Generated by Django 2.0.7 on 2018-08-20 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0035_person_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('type', models.CharField(max_length=255, verbose_name='Тип мероприятия')),
                ('start', models.DateTimeField(verbose_name='Дата и время начала')),
                ('end', models.DateTimeField(verbose_name='Дата и время завершения')),
                ('is_important', models.BooleanField(default=True, verbose_name='Явка обязательна?')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Включено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('participants', models.ManyToManyField(blank=True, to='theater.Person', verbose_name='Участники')),
                ('responsible_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_person', to='theater.Person', verbose_name='Ответственный за мероприятие')),
            ],
            options={
                'verbose_name': 'Внутреннее событие',
                'verbose_name_plural': 'Внутренние события',
            },
        ),
    ]
