# Generated by Django 2.0.7 on 2018-08-21 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0036_internalevent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='internalevent',
            options={'ordering': ('-created_at',), 'verbose_name': 'Внутреннее событие', 'verbose_name_plural': 'Внутренние события'},
        ),
    ]
