# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0002_auto_20171116_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='month_from',
            field=models.PositiveIntegerField(choices=[(1, 'Январь'), (2, 'Февраль'), (3, 'Март'), (4, 'Апрель'), (5, 'Май'), (6, 'Июнь'), (7, 'Июль'), (8, 'Август'), (9, 'Сентябрь'), (10, 'Октябрь'), (11, 'Ноябрь'), (12, 'Декабрь')], default=None, verbose_name='Месяц с'),
        ),
        migrations.AlterField(
            model_name='season',
            name='month_to',
            field=models.PositiveIntegerField(choices=[(1, 'Январь'), (2, 'Февраль'), (3, 'Март'), (4, 'Апрель'), (5, 'Май'), (6, 'Июнь'), (7, 'Июль'), (8, 'Август'), (9, 'Сентябрь'), (10, 'Октябрь'), (11, 'Ноябрь'), (12, 'Декабрь')], default=None, verbose_name='Месяц по'),
        ),
    ]
