# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 14:04
from __future__ import unicode_literals

import apps.theater.models
import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0003_auto_20171116_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('age', models.PositiveIntegerField(verbose_name='Возраст зрителей, от')),
                ('genre', models.CharField(blank=True, max_length=255, null=True, verbose_name='Жанр')),
                ('duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='Продолжительность, минут')),
                ('author', models.CharField(blank=True, max_length=255, null=True, verbose_name='Автор')),
                ('staging', models.CharField(blank=True, max_length=255, null=True, verbose_name='Инсценировка')),
                ('director', models.CharField(blank=True, max_length=255, null=True, verbose_name='Режиссёр')),
                ('head_of_production', models.CharField(blank=True, max_length=255, null=True, verbose_name='Руководитель постановки')),
                ('production_designer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Художник-постановщик')),
                ('lighting_designer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Художник по свету')),
                ('choreographer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Хореограф')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст')),
                ('image', models.ImageField(blank=True, help_text='Оптимальный размер: 740px*380px.', null=True, upload_to=apps.theater.models.Play.upload_to, verbose_name='Основное изображение')),
                ('free_enter', models.BooleanField(default=False, verbose_name='Свободный вход')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Спектакль',
                'verbose_name_plural': 'Спектакли',
            },
        ),
        migrations.CreateModel(
            name='PlayPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.theater.models.PlayPhoto.upload_to, verbose_name='Изображение')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Включено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('play', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theater.Play', verbose_name='Спектакль')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
    ]
