# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0007_auto_20171120_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play',
            name='duration',
            field=models.DurationField(blank=True, help_text='Используйте формат ЧЧ:ММ:СС', null=True, verbose_name='Продолжительность'),
        ),
    ]
