# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0009_auto_20171122_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='slug',
            field=models.SlugField(default='', help_text='Будет сгенерировано автоматически на основе поля "Название", если оставите поле пустым', max_length=255, verbose_name='Slug (для url)'),
        ),
    ]
