# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 11:34
from __future__ import unicode_literals

import apps.theater.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0011_auto_20171122_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='music',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Музыкальное оформление'),
        ),
        migrations.AlterField(
            model_name='play',
            name='image',
            field=models.ImageField(blank=True, help_text='Оптимальный размер: 800px*500px.', null=True, upload_to=apps.theater.models.Play.upload_to, verbose_name='Основное изображение'),
        ),
        migrations.AlterField(
            model_name='playphoto',
            name='image',
            field=models.ImageField(help_text='Оптимальный размер: 800px*500px.', upload_to=apps.theater.models.PlayPhoto.upload_to, verbose_name='Изображение'),
        ),
    ]
