# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 12:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0021_auto_20171128_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personplayrole',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theater.Person', verbose_name='Актёр'),
        ),
        migrations.AlterField(
            model_name='personplayrole',
            name='role',
            field=models.CharField(default=None, max_length=255, verbose_name='Роль'),
            preserve_default=False,
        ),
    ]
