# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-06 18:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0029_auto_20171228_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_actor',
            field=models.BooleanField(default=False, help_text='Если выбрано, то на странице персоны активным пунктом меню будет Труппа, иначе - Художественная часть (если эти страницы существуют).', verbose_name='Является актёром'),
        ),
        migrations.AlterField(
            model_name='person',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theater.Position', verbose_name='Должность или звание'),
        ),
    ]
