# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-06 19:27
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0030_auto_20180106_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentplay',
            name='person',
        ),
        migrations.RemoveField(
            model_name='currentplay',
            name='play',
        ),
        migrations.RemoveField(
            model_name='lastplay',
            name='person',
        ),
        migrations.RemoveField(
            model_name='lastplay',
            name='play',
        ),
        migrations.RemoveField(
            model_name='person',
            name='current_plays',
        ),
        migrations.RemoveField(
            model_name='person',
            name='last_plays',
        ),
        migrations.AddField(
            model_name='person',
            name='cinema',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Роли в кино'),
        ),
        migrations.AddField(
            model_name='person',
            name='plays',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Спектакли СевТЮЗа'),
        ),
        migrations.DeleteModel(
            name='CurrentPlay',
        ),
        migrations.DeleteModel(
            name='LastPlay',
        ),
    ]
