# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-06 22:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0031_auto_20180106_2127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'ordering': ('season__year_from',), 'verbose_name': 'История сезона', 'verbose_name_plural': 'История'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('-created_at',), 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ('created_at',), 'verbose_name': 'Страница', 'verbose_name_plural': 'Страницы'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ('name',), 'verbose_name': 'Персона', 'verbose_name_plural': 'Персоны'},
        ),
        migrations.AlterModelOptions(
            name='play',
            options={'ordering': ('title',), 'verbose_name': 'Спектакль', 'verbose_name_plural': 'Спектакли'},
        ),
    ]
