# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-09 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0032_auto_20180107_0049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ('title',), 'verbose_name': 'Должность', 'verbose_name_plural': 'Должности'},
        ),
        migrations.AlterModelOptions(
            name='season',
            options={'ordering': ('year_from',), 'verbose_name': 'Сезон', 'verbose_name_plural': 'Сезоны'},
        ),
        migrations.AlterField(
            model_name='season',
            name='month_from',
            field=models.PositiveIntegerField(choices=[(1, 'Январь'), (2, 'Февраль'), (3, 'Март'), (4, 'Апрель'), (5, 'Май'), (6, 'Июнь'), (7, 'Июль'), (8, 'Август'), (9, 'Сентябрь'), (10, 'Октябрь'), (11, 'Ноябрь'), (12, 'Декабрь')], default=9, verbose_name='Месяц с'),
        ),
        migrations.AlterField(
            model_name='season',
            name='month_to',
            field=models.PositiveIntegerField(choices=[(1, 'Январь'), (2, 'Февраль'), (3, 'Март'), (4, 'Апрель'), (5, 'Май'), (6, 'Июнь'), (7, 'Июль'), (8, 'Август'), (9, 'Сентябрь'), (10, 'Октябрь'), (11, 'Ноябрь'), (12, 'Декабрь')], default=5, verbose_name='Месяц по'),
        ),
    ]
