# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-09 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0033_auto_20180109_2024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ('title',), 'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.AlterField(
            model_name='person',
            name='has_page',
            field=models.BooleanField(default=True, verbose_name='Есть собственная страница'),
        ),
    ]
