# Generated by Django 2.0.7 on 2018-09-09 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0037_auto_20180821_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalevent',
            name='show_for_all',
            field=models.BooleanField(default=False, verbose_name='Показывать всем в служебном кабинете?'),
        ),
    ]
