# Generated by Django 2.2.17 on 2021-01-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0038_internalevent_show_for_all'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='weight',
            field=models.PositiveSmallIntegerField(default=1000, help_text='Чем больше значение, тем выше страница в списке.', verbose_name='Вес'),
        ),
    ]
