# Generated by Django 2.2.17 on 2021-01-06 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0040_auto_20210106_1732'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
