# Generated by Django 2.2.17 on 2021-01-24 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0041_delete_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Тип спектакля',
                'verbose_name_plural': 'Типы спектакля',
            },
        ),
        migrations.AddField(
            model_name='play',
            name='play_types',
            field=models.ManyToManyField(blank=True, to='theater.PlayType', verbose_name='Типы спектакля'),
        ),
    ]
