# Generated by Django 2.2.17 on 2021-01-24 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0042_auto_20210124_1554'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playtype',
            options={'verbose_name': 'Тип спектакля', 'verbose_name_plural': 'Типы спектаклей'},
        ),
        migrations.AlterField(
            model_name='play',
            name='play_types',
            field=models.ManyToManyField(blank=True, to='theater.PlayType', verbose_name='Типы спектаклей'),
        ),
    ]
