# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-06 22:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ('created_at',), 'verbose_name': 'Страница', 'verbose_name_plural': 'Страницы'},
        ),
    ]
