# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-05 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название вакансии')),
                ('count', models.CharField(max_length=255, verbose_name='Количество необходимых кадров')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
        migrations.CreateModel(
            name='VacationsPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hr_contacts', models.TextField(verbose_name='Текст контактов специалиста по кадрам')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('vacations', models.ManyToManyField(blank=True, to='people.Vacations', verbose_name='Вакансии')),
            ],
            options={
                'verbose_name': 'Страница "Вакансии"',
                'verbose_name_plural': 'Страница "Вакансии"',
            },
        ),
    ]
