# Generated by Django 2.2.17 on 2021-01-06 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0009_auto_20180109_2238'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VacanciesPage',
        ),
        migrations.DeleteModel(
            name='Vacancy',
        ),
    ]
