# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLinksModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fb', models.CharField(blank=True, max_length=255, null=True, verbose_name='Facebook')),
                ('vk', models.CharField(blank=True, max_length=255, null=True, verbose_name='Вконтакте')),
                ('instagram', models.CharField(blank=True, max_length=255, null=True, verbose_name='Instagram')),
                ('ok', models.CharField(blank=True, max_length=255, null=True, verbose_name='Одноклассники')),
                ('twitter', models.CharField(blank=True, max_length=255, null=True, verbose_name='Twitter')),
                ('youtube', models.CharField(blank=True, max_length=255, null=True, verbose_name='Youtube')),
            ],
            options={
                'verbose_name': 'Ссылки на соц. сети',
                'verbose_name_plural': 'Ссылки на соц. сети',
            },
        ),
    ]
