# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_sociallinksmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallinksmodel',
            name='fb',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='sociallinksmodel',
            name='instagram',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='sociallinksmodel',
            name='ok',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Одноклассники'),
        ),
        migrations.AlterField(
            model_name='sociallinksmodel',
            name='twitter',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='sociallinksmodel',
            name='vk',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Вконтакте'),
        ),
        migrations.AlterField(
            model_name='sociallinksmodel',
            name='youtube',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Youtube'),
        ),
    ]
