# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-10 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_headersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='headersettings',
            name='ukgs_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на страницу "Главное управление культуры города Севастополя""'),
        ),
    ]
